name: MLOps CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mlflow dvc[gdrive] scikit-learn

      - name: Save service account credentials
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS_DATA }}" > sa.json

      - name: Pull dataset with DVC
        run: |
          DVC_GDRIVE_CREDENTIALS=sa.json dvc pull -r gdrive_remote

      - name: Run training with MLflow
        run: |
          python src/train.py