name: MLOps CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mlflow "dvc[gdrive]>=3.50.0" scikit-learn

      # (Opsional) Debug isi secret, pastikan valid JSON
      - name: Debug Secret Format
        run: |
          echo "$GDRIVE_CREDENTIALS_DATA" | jq . > /dev/null
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

      - name: Save service account credentials
        run: |
          mkdir -p .dvc
          echo "${{ secrets.GDRIVE_CREDENTIALS_DATA }}" > .dvc/sa.json

      - name: Configure DVC remote for service account
        run: |
          dvc remote modify gdrive_remote gdrive_use_service_account true
          dvc remote modify gdrive_remote gdrive_service_account_json_file_path .dvc/sa.json

      - name: Pull dataset with DVC
        run: |
          dvc pull -r gdrive_remote

      - name: Run training with MLflow
        run: |
          python src/train.py
