name: MLOps CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mlflow "dvc[gdrive]>=3.50.0" scikit-learn

      # (Opsional) Debug isi secret, pastikan kebaca sebagai JSON
      - name: Debug Secret Format
        run: |
          echo "$GDRIVE_CREDENTIALS_DATA" | jq . > /dev/null
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

      - name: Save service account credentials
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS_DATA }}" > $GITHUB_WORKSPACE/sa.json
        shell: bash

      - name: Pull dataset with DVC
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
        run: |
          dvc pull -r gdrive_remote

      - name: Run training with MLflow
        run: |
          python src/train.py
