name: MLOps CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mlflow dvc[all] scikit-learn

      - name: Setup GDrive credentials for DVC
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS }}" > sa.json
          mkdir -p .dvc
          echo '[remote "gdrive_remote"]' > .dvc/config.local
          echo '    gdrive_service_account_json_file = sa.json' >> .dvc/config.local

      - name: Pull dataset with DVC
        run: |
          dvc pull -r gdrive_remote

      - name: Run training with MLflow
        run: |
          python src/train.py