name: MLOps CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mlflow dvc[all] scikit-learn

      - name: Setup gdrive credential
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS }}" > sa.json
          dvc remote modify gdrive_remote gdrive_service_account_json_file sa.json

      - name: Pull dataset with DVC
        run: |
          dvc pull

      - name: Run training with MLflow
        run: |
          python src/train.py
